qtopiamail: compile fix, stricter private/public with g++-4.9
QMailStare::success is used from functions outside of the class,
so it is required to be public, see the following result:

/home/qtbuild/qtmoko/src/libraries/qtopiamail/qmailstore.h:166:26: error: 'QMail
Store::AttemptResult Success' is private
     enum AttemptResult { Success = 0, Failure, DatabaseFailure };
                          ^
/home/qtbuild/qtmoko/src/libraries/qtopiamail/qmailstore.cpp:811:17: error: with
in this context
     if ((result == QMailStore::Success) && !t.committed()) {

Signed-off-by: Andreas Kemnade <andreas@kemnade.info>